[versions]
# Jetbrains
jetbrains-kotlin = "1.9.0"
jetbrains-serialization-json = "1.5.1"
betterParse = "0.4.4"

[libraries]
# Jetbrains
jetbrains-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "jetbrains-serialization-json" }

# Others
betterParse = { module = "com.github.h0tk3y.betterParse:better-parse", version.ref = "betterParse" }